[참고 - 위키독스, PyTorch로 시작하는 딥러닝 입문 ](https://wikidocs.net/52460) 

In [ ]:
import torch

## 1. 곱셈 (Multiplication)
- Matrix Multiplication - 행렬 곱셈(`.matmul`)
- Multiplication - 원소 별 곱셈(`.mul`)

1-1) PyTorch Tensor Matrix Multiplication -  `matmul()`

In [ ]:
## 4-1) PyTorch Tensor 행렬 곱셈 -  matmul()
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


1-2) element-wise Multiplication - `*` or `mul()`
- 동일한 크기의 행렬이 동일한 위치에 있는 원소끼리 곱함


In [ ]:
# 서로로 다른 크기의 행렬이 브로드캐스팅이 된 후 -> element-wise 곱셈 수행
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

# # 브로드캐스팅 과정에서 m2 변경 
# [1]
# [2]
# ==> [[1, 1],
#      [2, 2]]

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## 2. 평균 (Mean) 
- Numpy에서의 사용법과 매우 유사
- ` .mean()`

In [ ]:
# 1차원 벡터
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [ ]:
# 2차원 행렬
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean())

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


In [ ]:
# dinemsion을 인자로 보는 경우
# dim=0 --> 첫번째 차원, '행'의미
# 인자로 dim을 준다면 해당 차원을 제거한다는 의미 = '열'만 남김
# ==> 0번 '행' 제거 후 '열'만 남김
# 기존 행렬 크기 (2, 2) ---> 열의 차원만 보존되면서 (1, 2) = (2,)와 같으며 벡터
print(t.mean(dim=0))


tensor([2., 3.])


In [ ]:
# # 실제 연산 과정
# t.mean(dim=0)은 입력에서 첫번째 차원을 제거

# [[1., 2.],
#  [3., 4.]]

# 1과 3의 평균을 구하고, 2와 4의 평균 구함
# 결과 ==> [2., 3.]

In [ ]:
print(t.mean(dim=1))

# # 실제 연산 결과는 (2 × 1)
# [1. 5]
# [3. 5]

# 하지만 (2 × 1)은 결국 1차원이므로 ----> (1 × 2)와 같이 표현

tensor([1.5000, 3.5000])


In [ ]:
print(t.mean(dim=-1))
# 마지막 차원을 제거한다는 의미 = 결국 '열'의 차원을 제거한다는 의미와 같음 

tensor([1.5000, 3.5000])


## 3. 덧셈 (Sum)

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print('원소 전체 덧셈: :', t.sum()) # 단순히 원소 전체의 덧셈을 수행
print('행 제거: ', t.sum(dim=0)) # 행을 제거
print('열 제거: ', t.sum(dim=1)) # 열을 제거
print('열 제거: ', t.sum(dim=-1)) # 열을 제거

원소 전체 덧셈: : tensor(10.)
행 제거:  tensor([4., 6.])
열 제거:  tensor([3., 7.])
열 제거:  tensor([3., 7.])


## 4. 최대 (Max) & 아그맥스 (ArgMax)
- 최대(Max)는 원소의 최대값 return
- 아그맥스(ArgMax)는 최대값 가진 index를 return


In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print('max: ', t.max(), '\n') # Returns one value: max
print('max & argmax: ',t.max(dim=0)) # Returns two values: max and argmax --> 첫번째 차원 제거

max:  tensor(4.) 

max & argmax:  torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [ ]:
# # [1, 1]가 무슨 의미인지 봅시다. 기존 행렬을 다시 상기해봅시다.
# [[1, 2],
#  [3, 4]]

# 첫번째 열에서 0번 인덱스는 1, 1번 인덱스는 3
# 두번째 열에서 0번 인덱스는 2, 1번 인덱스는 4
# 다시 말해 3과 4의 인덱스는 [1, 1]

In [ ]:
# Max, Argmax 각각 받기
print('Max: ', t.max(dim=0)[0]) 
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [ ]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
