[참고 - 위키독스, PyTorch로 시작하는 딥러닝 입문 ](https://wikidocs.net/52460) 

In [1]:
import torch

## 1) 1D with PyTorch

In [2]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [4]:
print('t.dim() :', t.dim())  # rank  --> 차원 확인 
print('t.shape : ', t.shape)  # shape --> 사이즈 확인 
print('t.size() : ', t.size()) # shape --> 사이즈 확인

t.dim() : 1
t.shape :  torch.Size([7])
t.size() :  torch.Size([7])


In [5]:
print(t[0], t[1], t[-1])  # 인덱스로 접근
print(t[2:5], t[4:-1])    # 슬라이싱
print(t[:2], t[3:])       # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2) 2D with PyTorch

In [6]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [7]:
print('t.dim() :', t.dim())  # rank  --> 차원 확인 
print('t.shape : ', t.shape)  # shape --> 사이즈 확인 
print('t.size() : ', t.size()) # shape --> 사이즈 확인

t.dim() : 2
t.shape :  torch.Size([4, 3])
t.size() :  torch.Size([4, 3])


In [8]:
print(t[:, 1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다.
print(t[:, 1].size()) # ↑ 위의 경우의 크기

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [9]:
print(t[:, :-1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져온다.

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## 3) 브로드캐스팅(Broadcasting)
크기가 다른 행렬 또는 텐서에 대해서 사칙 연산을 수행시 자동으로 크기 맞추어 연산 수행

 행렬 A, B
 - 덧셈과 뺄셈을 할 때 -> 두 행렬 A, B의 크기가 같아야함
 - 두 행렬이 곱셈을 할 때 -> A의 마지막 차원과 B의 첫번째 차원이 일치해야함

In [17]:
## 같은 크기일 경우
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])

print(f'm1.shape: {m1.shape} / m2.shape: {m2.shape}')
print(f'm1 + m2: {m1 + m2}')

m1.shape: torch.Size([1, 2]) / m2.shape: torch.Size([1, 2])
m1 + m2: tensor([[5., 5.]])


In [18]:
## 다른 크기의 행렬 연산 - Broadcasting
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]

print(f'm1.shape: {m1.shape} / m2.shape: {m2.shape}')
print(f'm1 + m2: {m1 + m2}')

m1.shape: torch.Size([1, 2]) / m2.shape: torch.Size([1])
m1 + m2: tensor([[4., 5.]])


In [19]:
## 다른 크기의 행렬 연산 - Broadcasting
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])

print(f'm1.shape: {m1.shape} / m2.shape: {m2.shape}')
print(f'm1 + m2: {m1 + m2}')

# # 브로드캐스팅 과정에서 실제로 두 텐서가 어떻게 변경되는지 보겠습니다.
# [1, 2]
# ==> [[1, 2],
#      [1, 2]]
# [3]
# [4]
# ==> [[3, 3],
#      [4, 4]]

m1.shape: torch.Size([1, 2]) / m2.shape: torch.Size([2, 1])
m1 + m2: tensor([[4., 5.],
        [5., 6.]])
